<a href="https://colab.research.google.com/github/Bhumireddysusmita/Day1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
empArr = np.empty((3, 4))
print(empArr)

[[4.22983069e-315 0.00000000e+000 7.87949646e+199 1.45874611e-094]
 [6.01347002e-154 6.01334435e-154 6.21064510e+175 4.31997326e-038]
 [5.98129678e-154 7.50189709e+247 5.22396576e+257 5.98129746e-154]]


In [40]:
full_arr=np.full((3,4),5)
print(full_arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [46]:
arr=np.zeros(4)
print(arr)


[0. 0. 0. 0.]


In [50]:
arr2=np.zeros((3,5),dtype=int)
print(arr2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [51]:
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [53]:
arr1=np.ones((4,3),dtype=int)
print(arr1)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [58]:
arr=np.array([[1,4],[3,4]])
row=[3,4]
print(row in arr.tolist())

True


In [67]:
arr=np.array([[1,2,3],[42,np.nan,np.nan]])
print(arr)
cleaned_arr=arr[~np.isnan(arr).any(axis=1)]
print(cleaned_arr)

[[ 1.  2.  3.]
 [42. nan nan]]
[[1. 2. 3.]]


In [75]:
arr=np.array([[[2,2,2],[2,2,2]]])
print(arr.shape)
arr2=np.squeeze(arr)
print(arr2.shape)


(1, 2, 3)
(2, 3)


In [83]:
arr=np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
arr1=repr(arr).count("8, 9, 4")
print(arr1)

1


In [85]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
print(np.bincount(x).argmax())

[1 2 3 4 5 1 2 1 1 1]
1


In [89]:
num1 = np.array([1, 2])
num2 = np.array([[10, 20],
                 [30, 40]])

for a, b in np.nditer([num1,num2]):
  print(a, ":", b)

1 : 10
2 : 20
1 : 30
2 : 40


In [90]:
a = np.array([1, 2])
b = np.array([4, 6])
res = np.array(np.meshgrid(a, b)).T.reshape(-1, 2)
print(res)

[[1 4]
 [1 6]
 [2 4]
 [2 6]]
